### PR TITLE
Form on FMS Pro page for requesting access to demo

### PR DESCRIPTION
**Pull request by zarino**
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/857

* Form is shown by default.
* If JavaScript is available, form is hidden behind another button, to save space.
* Submitting the form sends contact details to the enquiries email address, and automatically forwards the user on to the Demo site.

form

### CODE REVIEW

**Comment by wrightmartin** [comment]
- Is the URL ever given to the form submitter? Eg. if I get access to the demo site but don't bookmark it, or forget the URL will I be tempted to just fill out the form again and give us loads of duplicate information?

-How does the forward work? Is there anything like a 'you'll be redirected in 5 seconds, if it doesn't work click here' type thing?

**Comment by zarino** [comment]
> Is the URL ever given to the form submitter? Eg. if I get access to the demo site but don't bookmark it, or forget the URL will I be tempted to just fill out the form again and give us loads of duplicate information?

Nope, we don't tell you what the URL is. You can obviously look at the URL once you’ve been redirected, and can bookmark that, or search your browser history for it.

As for duplicate information – all these people are warm leads. If we get to the point where we’re being inundated by "This person requested access to the demo" emails, then we’ll be in a very good position indeed. The aim here is to notify us when people are using the demo site, so we can follow up with a "How did it go?" email afterwards. So, in a way, if people think they have to fill in their details _each time_ they want to access the demo site, then that’s _even better_ for us.

Unless @jukesie disagrees?

> How does the forward work? Is there anything like a 'you'll be redirected in 5 seconds, if it doesn't work click here' type thing?

You press the "Let me in" button, and the next thing you see is the Borsetshire demo site. There’s no thank-you, no timer, nothing. You just submit your details, and you’re in.

**Comment by zarino** [comment]
@dracos @davea The `success_url` behaviour now has a test :+1:

But I'm getting some weird warning about `numeric comparison` in the test output :-1:

```
    ok 4 - Content contains "Thank you for your enquiry"
    ok 5 - checking for 1 email(s) in the queue
    1..5
ok 21 - check email sent correctly with dest field set to us
Argument "" isn't numeric in numeric comparison (<=>) at /home/vagrant/fixmystreet/bin/../local/lib/perl5/Number/Format.pm line 599.
Argument "" isn't numeric in numeric comparison (<=>) at /home/vagrant/fixmystreet/bin/../local/lib/perl5/Number/Format.pm line 599.
Argument "" isn't numeric in numeric comparison (<=>) at /home/vagrant/fixmystreet/bin/../local/lib/perl5/Number/Format.pm line 599.
Argument "" isn't numeric in numeric comparison (<=>) at /home/vagrant/fixmystreet/bin/../local/lib/perl5/Number/Format.pm line 599.
Argument "" isn't numeric in numeric comparison (<=>) at /home/vagrant/fixmystreet/bin/../local/lib/perl5/Number/Format.pm line 599.
Argument "" isn't numeric in numeric comparison (<=>) at /home/vagrant/fixmystreet/bin/../local/lib/perl5/Number/Format.pm line 599.
    ok 1
    1..1
ok 22 - check user can be redirected to a custom URL after contact form is submitted
    ok 1
    1..1
ok 23 - check user can be redirected to a custom URL after contact form is submitted
1..23
ok
All tests successful.
```

I wonder why?

**Comment by dracos** [comment]
Change your redirect to another page from /reports - the data for that page hasn't been set up right at that point (could prevent those warnings but meh).

**Comment by zarino** [comment]
Aha! Will do!

**Comment by zarino** [comment]
Test now uses `/faq` rather than `/reports` to avoid the `numeric comparison` warnings.

Resulting email looks like:

screen shot 2017-07-20 at 12 14 14

**Comment by zarino** [comment]
@markcridge would like a Phone field to be added to the form.

**Comment by zarino** [comment]
Form now includes a "Contact phone number" field:

screen shot 2017-07-27 at 14 52 35

**Pull request merged**
