### PR TITLE
[Highways England] NHW035 Personal Details in Free Text 'Detail' Field

### PR DESCRIPTION
**Pull request by MorayMySoc**
This is part 1 of a series of requirements for HE to highlight to users that personal information should not be put into the text field.

* Highlights existing wording warning about personal details

https://github.com/mysociety/societyworks/issues/3098

[skip changelog]

### CODE REVIEW

**Review by davea — APPROVED** [review]

**Comment by dracos** [comment]
Just added another commit here to stick a required checkbox in at the appropriate point.

**Review by davea — APPROVED** [review]
✅

**Comment by dracos** [comment]
Sorry, me again - one more commit that redacts email/phone from NH reports. Seemed easier to do it here than base another PR off of it, but can split it out if need be.

**Review by davea — CHANGES_REQUESTED** [review]
Looks like it'll only catch the first phone number, not all of them:

image


This was the original text:
image

**Comment by dracos** [comment]
Doh!

**Review by davea — APPROVED** [review]
☎️ 🙅

**Pull request merged**
