### PR TITLE
Makes it possible to select all categories in a map page by clicking "All"

### PR DESCRIPTION
**Pull request by joesiltberg**
This makes the category selection behave more like the status selection. By clicking "All", all checkboxes are checked.

This makes it easier for a user to select "all except..."

I've tested this with and without category groups, but I've only tested on v3.0 (the changes in this file after 3.0 don't seem to conflict with this change though).

See also #2900

### CODE REVIEW

**Comment by dracos** [comment]
Thanks for this; don't have as much time as normal at present (having to homeschool!), but hopefully will be able to take a look at this at some point.

**Comment by joesiltberg** [comment]
No problem @dracos ! Take care and stay safe 💪

**Comment by dracos** [comment]
I've just written https://github.com/mysociety/jquery-multi-select/pull/22 which if that's acceptable and works would mean we could pass in the all flag instead of having to construct a variable consisting of all the options solely to be read back out again.

**Comment by joesiltberg** [comment]
Sounds good!

If I understand this correctly (sorry it was a while since I looked at this), this would mean we could skip my changes in this PR, and instead import a new version of web/vendor/jquery.multi-select.min.js to the project, and also update web/cobrands/fixmystreet/fixmystreet.js (in the make_multi function) to make use of the new all flag..?

Would you like me to try something like that in this PR? Or just close this?

**Comment by dracos** [comment]
Yep, that sounds about right! That PR has been merged, so yes, if you'd like to try it out and see if it works, please do.

**Comment by joesiltberg** [comment]
@dracos sorry for the delay. Now this PR is updated according to what we said above (using the new version of jquery-multi-select)

**Comment by dracos** [comment]
No need to apologise! This looks good, I've just been testing it and there's one issue I hadn't thought of (sorry), which is that if e.g. Everything is picked in the category dropdown, all the categories get added to the URL, rather than the nicer none-of-them (because in this situation none selected is same as all selected). I think this should be easy enough to fix at the FMS end by the thing that updates the URL on such a change spotting if everything is picked, or something like that, I can try and take a look soon.
(I only worry because I imagine passing all the categories to the backend is harder on the DB than having none passed, iyswim).

**Comment by joesiltberg** [comment]
Ahh yeah that would be nice if it could be solved. It might not help too much for the original use case for this issue however (selecting "all except..."), if the next thing the user does is deselect a category.

For that use case the preset alone should still be an improvement, since previously the users would manually click all the other categories, generating lots of requests.

**Comment by dracos** [comment]
I've just pushed an extra commit to this that should remove the categories from the URL/ajax if they are all selected, do let me know if that works for you.

**Review by davea — APPROVED** [review]
This looks great!

**Comment by joesiltberg** [comment]
Looks good to me too! @dracos did you want me to test the URL thing before you merge this?

**Comment by dracos** [comment]
Sorry for the delay, this is now merged, thanks!

**Pull request merged**
