### PR TITLE
[Bulky] Allow multiple bookings

### PR DESCRIPTION
**Pull request by dracos**
Fixes https://github.com/mysociety/societyworks/issues/3780 [skip changelog]
First adds ID to cancel URLs (so that you'll be able to choose which to cancel), then lists all bookings on bin day page (even though there's only one at this point), and then allow multiple bookings.

### CODE REVIEW

**Review by davea — CHANGES_REQUESTED** [review]
Though dates of existing bookings are greyed out when making a new booking, it is possible to amend a booking to be on the same date as an existing booking:

image

**Comment by dracos** [comment]
> Though dates of existing bookings are greyed out when making a new booking, it is possible to amend a booking to be on the same date as an existing booking

Weird, I added the code to Bulky.pm but not Bulky/Amend.pm - my guess is I was working on both of these at same time, then when I rebased multiple on top of amending I forgot to add this. Will look to see if they can share more of the code here.

**Comment by dracos** [comment]
Okay, added Bulky/Shared.pm in the Amend branch with no changes other than sharing all the form code it can between Bulky.pm and Bulky/Amend.pm - this then meant any pending dates were now disabled on the amend form as well. Then added new bit of code and test to /not/ disable the date of the report being amended.

**Review by davea — APPROVED** [review]
Looks good 👍 


One minor consideration is that if the property you're viewing already has a collection you have to sign in before you can see any details about it at all, including the date. But the multiple bookings process discloses the date of the existing booking by way of including as a grayed-out radio button. Wonder if it's worth hiding the date in that case? Probably not, but thought worth mentioning.

**Pull request merged**
