### PR TITLE
Liu brancch

### PR DESCRIPTION
**Pull request by warbl**
Please check the following:

- [ ] Whether this PR should include changes to any documentation, or the FAQ;
- [ ] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [ ] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [ ] Are the changes tested for accessibility?
- [ ] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog

Please check the contributing docs, and describe your pull request here.
Screenshots or GIF animations (using e.g. LICEcap) may be helpful.

Please include any issues that are fixed, using "fixes" or "closes" so that
they are auto-closed when the PR is merged.

Thanks for contributing!

### CODE REVIEW

**Comment by dracos** [comment]
[cf #2945]
Thanks for your interest in the FixMyStreet project. I can see you have started on your own cobrand templates, which is good :) As before, you almost certainly do not want to edit base templates files, the example configuration file (it breaks the tests), or the README, we can't accept the PR like that.

Some hopefully helpful comments on your cobrand .pm file:
* You should not use "Whitelabel" as a parent in your cobrand file, it is for lots of UK-specific code (as you can see, Whitelabel's own parent is "UKCouncils"); as you are just beginning, I recommend your parent should be Default.
* You do not need "council_url"; you probably don't need "council_area" either, though if your installation only covers the one body I guess it might work okay.
* You do not have a "Philadelphia" geocoder so you do not need get_geocoder; you should set parameters for e.g. the OSM geocoder using configuration options as explained in the documentation.
* "MasterMap" is a UK-specific map type, so you don't want that either (also MAP_TYPE can be set in general.yml, you do not need to set it in code); please get it working with the normal defaults first.
* You have set a path_to_pin_icons but have no pin images there, you do not need that function.
* I am not sure why you have set disable_resend_button or bypass_password_checks, neither of those should be necessary.

Hope that's helpful.

**Comment by warbl** [comment]
Hello! I'm sorry for the general clumsiness in the changes and I will be
working on a forked repo from now on. A few classmates and I are working on
this for a school project. I was wondering if you could shed some light on
an issue we ran into in setting up the Cobrand:
[image: image.png]

Thanks!

**Comment by dracos** [comment]
Hi, I'm afraid your image did not attach properly. Try leaving the update on fhe github PR instead of by email I guess.

**Comment by warbl** [comment]
Made a pull request with the error

**Pull request closed without merging**
