### PR TITLE
FixaMinGata updates

### PR DESCRIPTION
**Pull request by dracos**
For @jonkri to review.

### CODE REVIEW

**Comment by jonkri** [comment]
Thank you for this, Matthew! I will review this. :)

**Comment by jonkri** [comment]
This mostly worked out fine - thanks a lot, Matthew!

With [this submit.txt file](https://github.com/mysociety/fixmystreet/files/288409/submit.txt) (the order of content might matter in this file since there's a system that interprets this text file), and the latest translation from Transifex, and updating the upload and cache directories in general.yml to absolute paths, I could merge this with master and deploy it and pretty much be laughing. :) So if you merge this with master, we'll deploy that into production!

**Comment by dracos** [comment]
Yep, email template updated and translation pulled, hope that's helpful :)

**Comment by jonkri** [comment]
It was incredibly helpful, Matthew - thanks again! :)

**Pull request merged**
