### PR TITLE
Hide 'Show my name publicly' when reporting on behalf of another user

### PR DESCRIPTION
**Pull request by pezholio**
For mysociety/fixmystreetforcouncils#140

### CODE REVIEW

**Comment by davea** [comment]
Nice! I think it'd be clearer what's going on if the 'show my name publicly' tick box was always visible, and just simply unticked & disabled when reporting as another user. i.e., just the changes from 7d2b736d88938c8e846b3e00e9ce7cf4410f3825.

**Comment by pezholio** [comment]
Yeah, good idea. I'll get on that 👍

**Comment by pezholio** [comment]
@davea Happy to do this, but Github lets you squash and merge now - https://github.com/blog/2141-squash-your-commits

**Comment by davea** [comment]
Alas, by way of self-hosting our repositories we can't take advantage of such niceties :)

**Comment by pezholio** [comment]
Ah ha, no worries. Will squash the old fashioned way then 😄

**Pull request merged**
