### PR TITLE
Fix recent photos on alerts page overruning footer.

### LINKED ISSUE #1168: Recent photos sidebar on alerts page runs over the footer
Moving this from https://github.com/mysociety/FixMyStreet-Commercial/issues/336 because it affects all FMS installations. e.g.

screen shot 2015-07-30 at 16 42 51

Should be as simple as removing the sticky-sidebar class, so PR to follow!

### PR DESCRIPTION
**Pull request by stevenday**
Closes #1168

### CODE REVIEW

**Comment by dracos** [comment]
Yay. I think this could also remove the mentions of `alertindex` throughout (I assume the east sussex one won't apply any more either).

**Comment by stevenday** [comment]
@dracos thanks! I've removed that class, and other instances of the `.sticky-sidebar` being used for the alert page sidebar I found via grep.

**Comment by dracos** [comment]
Woo!

**Comment by dracos** [comment]
Merged in b748677

**Pull request closed without merging**
