### PR TITLE
[Waste] Line service consistency

### PR DESCRIPTION
**Pull request by lucascumsille**
Fixes: https://github.com/mysociety/societyworks/issues/3980

This PR keeps Peterborough styling for the bind days page without interfering with other cobrands. 

### Peterborough
https://github.com/mysociety/fixmystreet/assets/13790153/1c12f721-86eb-4f22-8163-29ba419e2044

### Bromley
https://github.com/mysociety/fixmystreet/assets/13790153/9267ab0b-b5ab-478c-8f29-3c9b3bfc9715

[skip changelog]

### CODE REVIEW

**Review by MorayMySoc — CHANGES_REQUESTED** [review]
Locally on FireFox, I'm getting a difference on the line length between the other bin types and bulky waste - so the bulky waste line covers the whole of the width of the screen whereas the others stop short (hopefully clear from attached images). In your video of Bromley, this appears to be the case in full size though didn't happen full size for me.

Screenshot from 2023-11-17 10-45-29
Screenshot from 2023-11-17 10-45-11

**Comment by lucascumsille** [comment]
Thanks @MorayMySoc I just added a fixup that should fix that issue =)
Screenshot 2023-11-20 at 07 44 22

**Review by MorayMySoc — APPROVED** [review]
Great - looks good

**Comment by dracos** [comment]
Looks like this was merged as 277f997dd4

**Comment by dracos** [comment]
This has made Brent go like this:
image

**Pull request closed without merging**
