### PR TITLE
[Bulky] Add ‘Location details’ page to booking wizard

### PR DESCRIPTION
**Pull request by davea**
Missed this previously!

[skip changelog]

### CODE REVIEW

**Comment by lucascumsille** [comment]
@davea it looks good to me. I agree that we should make that button pop up more and if we can reuse the drag photo element from FMS that should do it. Is that something we do using the FormHandler?

**Comment by davea** [comment]
Yes, I think we'll need to add the appropriate class to the element in the FormHandler field definition. I'll figure that out as part of https://github.com/mysociety/fixmystreet/pull/4092.

**Comment by davea** [comment]
In the end I did it in this PR - see cd827ccf2a93893d6b63a20376f47bbd90446a2c.

**Comment by lucascumsille** [comment]
Looking good @davea nice addition.
I added a commit so the dropzone doesn't use the whole width. Because of the size + background of element I thought it was bit much. If you checkout this branch you won't be able to see it, because the styling is being applied to the dropzone nested inside `body.bulky` and we haven't add that class to body in this PR.

Screenshot 2022-09-30 at 09 00 39

**Pull request merged**
