### PR TITLE
[FixaMinGata] cobrand customizations

### PR DESCRIPTION
**Pull request by joesiltberg**
A couple of customizations for FixaMinGata:

 1. Show staff user names in updates
 2. Don't scroll reports on load

This is my first delivery to the FixaMinGata cobrand. Let me know if you need some kind of approval from someone at FixaMinGata/Sambruk in some way.

### CODE REVIEW

**Comment by jonkri** [comment]
The changes look good to me. 🙂

**Comment by joesiltberg** [comment]
That would be great, thanks @dracos !

**Comment by dracos** [comment]
Should all be merged now, thanks!

**Comment by joesiltberg** [comment]
Super, and thanks for adding the test!

**Pull request merged**
