### PR TITLE
Use the default_to_body permission also when creating updates.

### LINKED ISSUE #3317: The permission default_to_body doesn't affect updates
**Describe the bug**
The description for the permission default_to_body is "Default to creating reports/updates as the council", but it only seems to be used when creating reports, not when posting updates.

When looking at the implementation for _creating reports_, I noticed that it defaults to creating as the council if the user is a staff user and has either planned_reports ("Manage shortlist") or default_to_body. This doesn't make sense to me, but I'll do the same for updates in my PR with a suggested fix. But shouldn't it be possible to let a user manage their shortlist and also default to creating reports/updates as themselves?

**To Reproduce**
1. Give a staff user permission to create reports/updates as the council
2. Give the same staff user permission to "Default to creating reports/updates as the council"
3. Login as that staff user and start to create an update, note that posting as "myself" is the selected default.

### PR DESCRIPTION
**Pull request by joesiltberg**
Fixes #3317

### CODE REVIEW

**Comment by dracos** [comment]
Thanks for this, good to be consistent between updates and reports! I'll take a look at the permissions thing as you mention on #3317.

**Comment by joesiltberg** [comment]
@dracos I've decoupled the planned_reports and default_to_body permissions now and updated the changelog.

I also needed to add a commit for triggering an on change event for the "contribute as" select, to make sure the controls are correct from the start when a staff user has the default_to_body permission. See the change in fixmystreet.js. I'm not sure if this is the best way of doing this but it seemed to work.

**Comment by joesiltberg** [comment]
Latest push was just to rebase and resolve conflict in the CHANGELOG.

@dracos I consider this ready to be merged, if you approve of the changes.

**Comment by joesiltberg** [comment]
@dracos oops, looks like there's at least one relevant failing test. I'll have a look at it, sorry!

**Comment by joesiltberg** [comment]
@dracos the failing test has been addressed now.

**Comment by dracos** [comment]
Hiya - if you can give me permission to edit your PR branch, I'll tidy this up before merging (the two things I'll do is combine the changelog/test commits to be with their relevant code changes, and move the JS call you've added to staff.js, there's a little hook in there where staff-based display:report things run).

**Comment by joesiltberg** [comment]
@dracos It seems it's not allowed since the fork is owned by an org and not my personal account. I've invited you as contributor to our fork for now, hope that's ok. Thanks for the help!

**Comment by joesiltberg** [comment]
Thanks for the help, looks good to me!

**Comment by joesiltberg** [comment]
@dracos oops! I think we forgot about this PR. I rebased it now and resolved conflicts in CHANGELOG. Hopefully the tests still pass :-)

**Comment by joesiltberg** [comment]
Ping @dracos in case you haven't seen it. Also reminder that you might need to alter some permissions in your production database before deploying this (see your two comments March 23 in #3317)

**Comment by dracos** [comment]
Sorry for the delay in this, going to get in on master today. Hopefully okay for me to force push?

**Comment by dracos** [comment]
Done! Sorry again for the delay.

**Pull request merged**
