### PR TITLE
[Northumberland] Added styling for FMS and emails

### PR DESCRIPTION
**Pull request by lucascumsille**
Front-end for Northumberland
Fixes: https://github.com/mysociety/societyworks/issues/3455

### Notes

- In their [current website ](https://www.northumberland.gov.uk/Home.aspx) they are quite minimalistic when using colours, blue for interaction and yellow for warning, besides that is pretty much grey scale.
- I wasn't too sure if the file `site-name` was necessary, I tried to erase but then the name in the text in the logo would FixMyStreet. Let me know if there is a workaround and I'll erase the file.

Let me know if there is any feedback =)

### Preview
Screenshot 2023-02-06 at 06 50 31

Screenshot 2023-02-06 at 06 50 48

Screenshot 2023-02-06 at 06 51 07
Screenshot 2023-02-06 at 06 51 18

Screenshot 2023-02-06 at 06 51 59

### Emails
Screenshot 2023-02-06 at 06 53 23
Screenshot 2023-02-06 at 06 53 00

### CODE REVIEW

**Comment by dracos** [comment]
> I wasn't too sure if the file site-name was necessary, I tried to erase but then the name in the text in the logo would FixMyStreet. Let me know if there is a workaround and I'll erase the file.

`git grep site_name templates/web` will show you everywhere the site-name.html template is used. It is necessary if the service has a custom name that isn't FixMyStreet, e.g. Streetcare or "Report it", whatever the cobrand calls it, and is used in a few different places. So in header-logo.html in this case I wouldn't use `site_name`, you can replace that with the name of the council directly. Similarly, templates/email/*/site-name.txt is a site name used in emails.

**Comment by lucascumsille** [comment]
> > I wasn't too sure if the file site-name was necessary, I tried to erase but then the name in the text in the logo would FixMyStreet. Let me know if there is a workaround and I'll erase the file.
> 
> `git grep site_name templates/web` will show you everywhere the site-name.html template is used. It is necessary if the service has a custom name that isn't FixMyStreet, e.g. Streetcare or "Report it", whatever the cobrand calls it, and is used in a few different places. So in header-logo.html in this case I wouldn't use `site_name`, you can replace that with the name of the council directly. Similarly, templates/email/*/site-name.txt is a site name used in emails.

Thanks @dracos =) I got rid of the file and just changed the name directly.

**Comment by lucascumsille** [comment]
@jacquelinebylau Just in case, the focus state for this cobrand are bit different to their current website. The reason was to make it more accessible for visual impaired and colour blind users.

**Review by chrismytton — APPROVED** [review]
Thanks @lucascumsille! ✨ 

I'm going to merge this into a `northumberland-reviewed` branch. So as with Camden, please create any future pull requests from that branch. Thanks!

**Comment by lucascumsille** [comment]
> Thanks @lucascumsille! ✨
> 
> I'm going to merge this into a `northumberland-reviewed` branch. So as with Camden, please create any future pull requests from that branch. Thanks!

Awesome =) Thanks Chris. I'll do that then.

**Pull request merged**
