### PR TITLE
[Buckinghamshire] Remove custom map bits

### PR DESCRIPTION
**Pull request by chrismytton**
Bucks are looking to switch to OS Maps, so remove the custom map bits so it uses the default map setup. [skip changelog]

### CODE REVIEW

**Review by dracos — CHANGES_REQUESTED** [review]
Hooray! Though should also remove web/js/map-wmts-buckinghamshire.js (and then update t/map/tests.t too) :)

**Review by dracos — APPROVED** [review]
🍁

**Comment by chrismytton** [comment]
Changed the `default_map_zoom` in cobrand and `max_resolution` in JS, as discussed in Slack, so requesting another review!

**Comment by dracos** [comment]
Looks like zoom change etc has broken the front end test in some way, presumably something is now no longer where it used to be.

**Review by dracos — CHANGES_REQUESTED** [review]
Looks like zoom change etc has broken the front end test in some way, presumably something is now no longer where it used to be.

**Comment by chrismytton** [comment]
I don't fully understand why this test passes on master, but with this change to the maps the road-placement message is triggered, so have to give an answer to that extra step in this test in order for it to pass.

**Review by dracos — APPROVED** [review]
"I don't fully understand why this test passes on master" - I guess as the zoom level is now different, the map click (at x/y coordinates) is now clicking in a different place, and before it wasn't actually clicking somewhere that was "Bucks" mocked so was just generic categories? That's all I can think of anyway, so sounds like it might be more accurate now?

**Pull request merged**
