### PR TITLE
[Surrey] Extra configuration

### PR DESCRIPTION
**Pull request by MorayMySoc**
Surrey FMS: click map wording
https://github.com/mysociety/societyworks/issues/4304

Contact and privacy information
https://github.com/mysociety/societyworks/issues/4305
This is also on servers in `surrey-config` branch

point FMS to tellus.surreycc.gov.uk
https://github.com/mysociety/societyworks/issues/4299
In `surrey-config` 

[skip changelog]

### CODE REVIEW

**Review by davea — CHANGES_REQUESTED** [review]
These commits in FMS look ok. However the `surrey-config` branch has a couple of issues:

 - wrong email address for `contact_email` (missing `f` prefix)
 - DNS hasn't been updated with `surrey.fixmystreet.com` record.
 - Additionally this `surrey-config` branch cannot be merged and deployed until the client correctly configures their DNS record, as until then it will break SSL certificate renewal.

**Comment by MorayMySoc** [comment]
I've update the `surrey_config` but can't run `/usr/sbin/named-checkzone` to check the dns as don't have permissions...

**Review by davea — APPROVED** [review]
These changes and yours on `surrey-config` look good! Please don't merge the latter until the DNS issue has been resolved though.

**Comment by lizettal** [comment]
@davea we spoke about this last week and you were going to have a look at how to merge everything except the one affected by the DNS settings

**Pull request merged**
