### PR TITLE
[Surrey] Add HappyOrNot

### PR DESCRIPTION
**Pull request by davea**
For https://github.com/mysociety/societyworks/issues/4420

[skip changelog]

### CODE REVIEW

**Review by dracos — CHANGES_REQUESTED** [review]
This 3rd-party JS directly uses the `?.` operator, which only exists in Chrome 80+, Safari 13+ etc, not Cypress anyway, so breaks the Cypress tests @MorayMySoc has added in https://github.com/mysociety/fixmystreet/pull/5118 (and any old browser).

The domain could/should be added to the block list for Cypress, but then the second line here will need at least `window.HappyOrNot && ` adding at the start to stop it erroring when the object is missing.

I also don't know why the language is set to Finnish (fi-FI) ;)

**Comment by dracos** [comment]
Test files should not be loading/calling external 3rd-party JS at all, think how many times these tests might be being run, so please add it to the block list as well (which should be fine given the change you have already made to deal with it not loading/erroring).

**Comment by MorayMySoc** [comment]
I think that should be it in 1ab153f3324976b0a34f5cb9ff632b78215951dc ?

**Comment by dracos** [comment]
Ah, sorry, you did say you'd put it direct on the surrey-cobrand branch. Guess would have been good to be on this PR as well :)

**Pull request merged**
