### PR TITLE
Per-report OpenGraph images

### LINKED ISSUE #2394: Allow per-report OpenGraph images
Continuing from #613 - that switched to a new default image for all pages, but we think it's desirable to allow report pages to use the report image, if provided, and the default if not.

### PR DESCRIPTION
**Pull request by gbp**
Fixes #2394:

Please check the following:

- [x] Whether this PR should include changes to any documentation, or the FAQ;
- [x] All cobrand-specific commits start their commit message with the cobrand in square brackets;
- [x] Is new functionality tested? CodeCov will warn you about the diff coverage, but won’t complain about e.g. new files;
- [x] Are the changes tested for accessibility?
- [x] Have you updated the changelog? If this is not necessary, put square brackets around this: skip changelog

### CODE REVIEW

**Comment by gbp** [comment]
@dracos not really sure where to start with implement tests for this as there doesn't seem to be much coverage around the image generation yet. Could you confirm if the cobrands which override `header_opengraph_image.html` should also have this feature?

**Comment by dracos** [comment]
"not really sure where to start with implement tests for this as there doesn't seem to be much coverage around the image generation yet." - hmm, yeah, think the tests assume IM isn't present; the shrink/resize just return themselves, which I guess is better than nothing; you could do something similar, perhaps, with the sample image the tests use, check that at least gets output as you'd expect, that'd probably do.

"Could you confirm if the cobrands which override header_opengraph_image.html should also have this feature?" - yeah, might as well be consistent, they can always switch it away if they decide they don't want it.

**Comment by gbp** [comment]
> the shrink/resize just return themselves, which I guess is better than nothing; you could do something similar, perhaps, with the sample image the tests use, check that at least gets output as you'd expect, that'd probably do.

I attempted to:
```diff
diff --git a/t/app/model/photoset.t b/t/app/model/photoset.t
index 29a28d232..88a902395 100644
--- a/t/app/model/photoset.t
+++ b/t/app/model/photoset.t
@@ -96,5 +96,17 @@ subtest 'Correct storage backends are instantiated' => sub {

 };

+subtest 'Photoset get Opengraph image data' => sub {
+    my $photo = path('t/app/controller/sample.jpg')->slurp_raw;
+    my $photoset = FixMyStreet::App::Model::PhotoSet->new({
+        data_items => [ $photo ],
+    });
+
+    my $data = $photoset->get_image_data( num => 0, size => 'og' );
+
+    is $data->{width}, 1200, 'width is 1200';
+    is $data->{height}, 630, 'height is 630';
+};
+

 done_testing();
```

But this isn't working due to [ImageMagick being disabed](https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/ImageMagick.pm#L6) in test mode. Not really sure how/where else I should be testing this.

**Comment by dracos** [comment]
I think it'd be fine if it tests the basics by fetching a report page, and checking that e.g. the right image URL is being given in the opengraph line. The only alternative would be to use e.g. Image::Size to read the width/height instead (that's used at the point of image upload), which doesn't feel worth it.

**Comment by davea** [comment]
I've added a couple of simple tests as suggested. Could you give this a review please @dracos?

**Pull request merged**
