### PR TITLE
[Lincolnshire] Change default_map_zoom

### PR DESCRIPTION
**Pull request by chrismytton**
Lincolnshire have requested that the map be more zoomed in by default.

Fixes https://github.com/mysociety/societyworks/issues/3173

### CODE REVIEW

**Review by MorayMySoc — APPROVED** [review]
All good!

**Review by MorayMySoc — CHANGES_REQUESTED** [review]
Ooops...failing cypress test. Might just be a glitch but best to check

**Comment by chrismytton** [comment]
> Ooops...failing cypress test. Might just be a glitch but best to check

Re-ran the tests and they're passing this time, so just a transient Cypress glitch it seems!

**Review by MorayMySoc — APPROVED** [review]
Really all good

**Pull request merged**
