### PR TITLE
Accessibility related smörgåsbord of things

### PR DESCRIPTION
**Pull request by dracos**
Fixes https://github.com/mysociety/societyworks/issues/3438
Fixes https://github.com/mysociety/societyworks/issues/3436
Fixes https://github.com/mysociety/societyworks/issues/3433
Fixes https://github.com/mysociety/societyworks/issues/3432 (I think)
Fixes https://github.com/mysociety/societyworks/issues/3430
Fixes https://github.com/mysociety/societyworks/issues/3429

### CODE REVIEW

**Comment by lucascumsille** [comment]
Hey @dracos Regarding this commit
[Add visually-hidden nearest address in report list](https://github.com/mysociety/fixmystreet/pull/4283/commits/2721aa6a5c3622875b2bab33b8191988334ac907)

It doesn't retrieve the nearest address for me, I also tried using the button "Use my nearest location", but that didn't work either. Do I need to enable something?

**Comment by lucascumsille** [comment]
- [ ] Fixes https://github.com/mysociety/societyworks/issues/3436
- [ ] Fixes https://github.com/mysociety/societyworks/issues/3433
- [ ] Fixes https://github.com/mysociety/societyworks/issues/3432 (I think)
- [ ] Fixes https://github.com/mysociety/societyworks/issues/3430
- [ ] Fixes https://github.com/mysociety/societyworks/issues/3429

**Comment by dracos** [comment]
Sorry, wasn't clear what that's doing - on an /around or /reports list page, existing reports will have their closest address (if pre-calculated) added to their entry in their list, visually hidden. The pre-calculation only happens when a report is actually sent to a body, which is why you might not have any in your local development.

**Comment by lucascumsille** [comment]
> Sorry, wasn't clear what that's doing - on an /around or /reports list page, existing reports will have their closest address (if pre-calculated) added to their entry in their list, visually hidden. The pre-calculation only happens when a report is actually sent to a body, which is why you might not have any in your local development.

Great thank Matthew, makes sense.

**Comment by lucascumsille** [comment]
@dracos sorry it's taking me long.
I get why in this [commit](https://github.com/mysociety/fixmystreet/pull/4283/commits/21c69586dbcb3a213c6dcd62000ba16e5ac8b5c6) we got rid of the fieldsets when we didn't have a group. But was a reason to do get rid of it in files like `index.html` when we could have included a legend?

**Comment by dracos** [comment]
No worries! A fieldset is to group related controls/labels (e.g. all the radio inputs for a particular question, or if you had a few text inputs all about parts of the user's address, say). I don't think it should be used to group every control within a form, that seems superfluous/confusing. In contact/index.html (and the other cases), I think that's what it's doing. This does make me realise additionally though that `contact/who.html` is /missing/ a fieldset and should have one there to wrap its radio buttons.

**Comment by lucascumsille** [comment]
> No worries! A fieldset is to group related controls/labels (e.g. all the radio inputs for a particular question, or if you had a few text inputs all about parts of the user's address, say). I don't think it should be used to group every control within a form, that seems superfluous/confusing. In contact/index.html (and the other cases), I think that's what it's doing. This does make me realise additionally though that `contact/who.html` is /missing/ a fieldset and should have one there to wrap its radio buttons.

That makes sense =). Regarding the `contact/who.html`, I checked `templates/web/fixmystreet.com/contact/who.html`, and we don't have a fieldset for that group in the file, but when a inspected https://www.fixmystreet.com//contact, I noticed that we do have a fieldset(wrapping the whole form) with not legend right after the `form` tag. Not sure where that it's coming from.
Screenshot 2023-02-16 at 06 36 22

**Comment by dracos** [comment]
"I noticed that we do have a fieldset(wrapping the whole form) with not legend right after the form tag. Not sure where that it's coming from." - that's the one I've removed in this PR in templates/web/base/contact/form.html.

**Comment by lucascumsille** [comment]
@dracos Looks good. Before I approve, I wanted to check if some these files should also have fieldsets: 

- `/web/base/dashboard/index.html` line 100-105: To wrap  the start/ end date?
- `templates/web/base/my/my.html` line 64-77: Receive update notifications
- `templates/web/base/questionnaire/creator_fixed.html` line 12-17
- `templates/web/base/questionnaire/index.html` line 37-44, 63-69, 83-88

**Comment by dracos** [comment]
Yeah, looks like all of those should have a fieldset.

**Pull request merged**
