### PR TITLE
[TfL] Improve email design

### PR DESCRIPTION
**Pull request by chrismytton**
- Change TfL to Transport for London
- Add TfL logo
- Change emails to say Street Care rather than FixMyStreet

Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1670

image

### CODE REVIEW

**Comment by chrismytton** [comment]
> One typo in a commit message s/stay/say/ is all :)

Oops, copied that straight from the original issue without checking!

**Comment by chrismytton** [comment]
@wrightmartin Would you mind reviewing the screenshot in the original comment please?

I'd like to check that it matches the TfL branding guidelines, e.g. does the TfL logo need aligning in a certain way or anything like that?

**Comment by chrismytton** [comment]
I guess it might look better if the logo is a bit more aligned with the text regardless of what the guidelines say?

**Comment by wrightmartin** [comment]
> I guess it might look better if the logo is a bit more aligned with the text regardless of what the guidelines say?

**Comment by chrismytton** [comment]
Thanks @wrightmartin, I've updated it with the new logo you gave me. Looking much better now!

image

**Pull request merged**
