### PR TITLE
Oxfordshire photo guidance

### PR DESCRIPTION
**Pull request by zarino**
Fixes mysociety/fixmystreetforcouncils#6

screen shot 2016-09-08 at 11 48 37

Adds the photo guidance from FMS.com and also pluralizes the "Photos" label for all cobrands.

### CODE REVIEW

**Comment by davea** [comment]
Is it worth adding the new guidance for all UK cobrands by putting it in `fixmystreet-uk-councils` instead of `oxfordshire`?

Also, don't forget the update form can have multiple photos too.

**Comment by dracos** [comment]
Is it worth putting the guidance on all cobrands, in fact?

**Comment by zarino** [comment]
Ok, the "Photos" pluralisation should now be in place wherever the dropzone component appears.

And I've moved the `after_photo.html` into `base`, so it should appear for every cobrand now. @davea can you think of any cobrands that won't want to show this?

**Comment by dracos** [comment]
Now it's in base,it'll need marking for translation.

**Comment by zarino** [comment]
@dracos: Done!

**Pull request merged**
