### PR TITLE
[Bromley] [Waste] Fix bookings marked payment failed not being cancelled.

### PR DESCRIPTION
**Pull request by neprune**
[skip changelog] [FD-2623](https://mysocietysupport.freshdesk.com/a/tickets/3623)

### CODE REVIEW

**Review by dracos — CHANGES_REQUESTED** [review]
Thanks, think this is simpler - now it's here I note one thing that might have to change, which is the "Cancelled at user request" and "Booking cancelled by customer" texts probably should perhaps only be "Cancelled" and "Booking cancelled" in this situation.

**Review by dracos — CHANGES_REQUESTED** [review]
Sorry, I wasn't clear, by "in this situation" I meant have "Booking cancelled" for when this script causes it, but leave it with '.by customer' for when the customer has cancelled it (useful information to have). Looks like test is failing anyway, so hopefully can change while doing that.

**Comment by dracos** [comment]
(Oh, no, looks like test failure is unrelated, from @chrismytton mention yesterday as to something)

**Comment by neprune** [comment]
> Sorry, I wasn't clear, by "in this situation" I meant have "Booking cancelled" for when this script causes it, but leave it with '.by customer' for when the customer has cancelled it (useful information to have). Looks like test is failing anyway, so hopefully can change while doing that.

Sorry, complete brain failure on my part, I think you were clear.

**Pull request merged**
