### PR TITLE
Add geolocate button to recentre map at current position

### PR DESCRIPTION
**Pull request by davea**
For https://github.com/mysociety/societyworks/issues/3783

### CODE REVIEW

**Comment by davea** [comment]
Wasn't really sure what to do about animating the loading spinner for non-SVG browsers... Could do a GIF I suppose.

**Comment by dracos** [comment]
"Wasn't really sure what to do about animating the loading spinner for non-SVG browsers" - seems doubtful an IE11 user will also be wanting to use geolocation, I reckon :)

**Comment by davea** [comment]
Don't know what the `responsive.js` test failure is about - it's fine here at least. Have just pushed a little fixup so hopefully it was a one-off...

**Review by dracos — APPROVED** [review]
Works very nicely :)

**Pull request merged**
