### PR TITLE
[Peterborough] Allow payment to be taken for collection bookings

### PR DESCRIPTION
**Pull request by davea**
- [x] Tests

For https://github.com/mysociety/societyworks/issues/3282
For https://github.com/mysociety/societyworks/issues/2912
For https://github.com/mysociety/societyworks/issues/3313

[skip changelog]

### CODE REVIEW

**Comment by dracos** [comment]
Have added a commit for staff payments, I think.

**Comment by dracos** [comment]
Have added pay designs from #4122, and consolidated the bulky confirmation page to hopefully just one.

**Comment by dracos** [comment]
@davea Can't ask you for review as your own PR, but presumably you want to look at the staff payment/design things on top.

**Comment by davea** [comment]
PAYE and design changes look good to me 👍

I've done the [payment redirection notice (#3313)](https://github.com/mysociety/societyworks/issues/3313) and added it as a [commit](https://github.com/mysociety/fixmystreet/pull/4129/commits/bb30b9cedf8d7d98807bda61618c241c28527839) here, hope that's OK.

**Review by dracos — APPROVED** [review]

**Pull request merged**
