### PR TITLE
[Shropshire] Ensure all staff users set a password

### PR DESCRIPTION
**Pull request by davea**
(This has the side effect of requiring users to change their password after ~10 years, but I think that'll be OK.)

[skip changelog]

### CODE REVIEW

**Review by MorayMySoc — CHANGES_REQUESTED** [review]
This forces a user to set a password, but it doesn't force them to use it as they can still log in by requesting a link get sent to their email address to log in with. Also, if the user follows the forgotten password link, they can use a compromised email address to log in. I guess if those options were removed, an admin could then send a login email by request and a password could be reset that way?

**Comment by davea** [comment]
I thought about this a bit more and can't think of a sensible way to disable email login for staff that doesn't also disable it for members of the public.

 - Maybe some JS that only reveals the "email me a link to sign in" text when a non-`@shropshire.gov.uk` email is entered?
   - feels quite clunky and surprising, and has accessibility issues
 - Maybe show an error page to users who enter a `@shropshire.gov.uk` address and click the "email me a link to sign in" or "forgotten password" link?
   - Probably would be quite irritating

**Comment by MorayMySoc** [comment]
I suppose the actual content of the emails for 'forgotten password' and 'send link to sign in' could test for Shropshire and just give a policy notice instead of links.

**Comment by dracos** [comment]
I'm going to assume this was decided not to be taken forward

**Pull request closed without merging**
