### PR TITLE
[Rutland] Branded email templates

### PR DESCRIPTION
**Pull request by zarino**
Fixes mysociety/fixmystreet-commercial#972.

I’ve used the (crest-less) logo that they’re currently using on their website, rather than the (crest-ful) logo currently being applied in the cobrand web header.

screen shot 2018-02-08 at 12 01 40
[skip changelog]

### CODE REVIEW

**Comment by davea** [comment]
That big yellow box should probably be omitted given we do integrate with Rutland.

**Comment by zarino** [comment]
@davea @dracos Ah, do we want the "Where did this report come from?" and "Is there a better contact address?" gone too?

**Comment by dracos** [comment]
TBH, I don't think we'll be sending reports via email, so this'll never be seen :)

**Comment by zarino** [comment]
> TBH, I don't think we'll be sending reports via email, so this'll never be seen :)

@dracos I assume this is why `_submit_footer.html` hasn’t been overridden in the Oxfordshire cobrand either – because `submit.html` isn’t actually used any more in cobrands with full integration?

**Pull request merged**
