### PR TITLE
Locale pt BR fully translated

### PR DESCRIPTION
**Pull request by halkernel**
Hello, I have forked your repository and also I have been working on translating and customizing in order to have it working in Brazil. As I finished the translation I found would be important have it in the main repository of FixMyStreet, thus, pt PT could use as example, and other countries that speak Portuguese would also be able to have an reference on translation. It took much time, so let me know if you need anything else to merge it.

Also, I have sent for a master in Letters (a friend of mine) for reviewing the translation. As soon as I have it (probably would take a while) I will open another PR with the properly contribution and reference to the person. 

I can be contacted via kennet.emerson@gmail.com if necessary.

### CODE REVIEW

**Comment by halkernel** [comment]
@chrismytton @dracos

**Comment by dracos** [comment]
Hiya, thanks very much for this! We'll look to get it merged soon. We also use Transifex for people to provide translations - just checking you haven't updated anything there, so I can update what we store there with what you have done here? Thanks again.

**Comment by halkernel** [comment]
Hey, @dracos. Yeah, you're right, I didn't update anything in there. Feel free to update and store there or wherever is needed. Let me know if you need anything else, and feel free to close the PR also when you merge it.

**Comment by dracos** [comment]
Hi there, I rebased your commit on top of current master and reworded the commit to explain its contents rather than the "preparing branch" text. So this has now been merged as b93e33f8b, you can reset your branch to that/upstream. Thanks very much!

**Pull request closed without merging**
